import type { ThemeMode } from '../types';
import { storage } from './storage';
import { ACCENT_TOKENS, DEFAULT_ACCENT, RECENT_ACCENTS_MAX, isAccentId, type AccentId } from '../constants/accents';
import palette from '../constants/accentPalette.json';

export type ResolvedTheme = 'light' | 'dark';

/** 'system' follows the OS; with no OS preference the app is light. */
export function resolveTheme(mode: ThemeMode, win: Window = window): ResolvedTheme {
  if (mode !== 'system') return mode;
  return win.matchMedia?.('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}

/** An accent preset's token values for a theme (accentPalette.json, generated by npm run accents). */
export function accentTokens(accent: AccentId, theme: ResolvedTheme): Record<string, string> {
  const values = (palette[accent] ?? palette[DEFAULT_ACCENT])[theme];
  return Object.fromEntries(ACCENT_TOKENS.map((name, i) => [name, values[i]]));
}

/**
 * Applies a theme and an accent to a document (the main window, the mini player's PiP
 * window, the alert island). The accent's tokens are set inline on the root, over tokens.css.
 */
export function applyTheme(mode: ThemeMode, accent: AccentId, doc: Document = document): ResolvedTheme {
  const resolved = resolveTheme(mode, doc.defaultView ?? window);
  const root = doc.documentElement;
  root.dataset.theme = resolved;
  root.style.colorScheme = resolved;
  for (const [name, value] of Object.entries(accentTokens(accent, resolved))) root.style.setProperty(name, value);
  return resolved;
}

const isThemeMode = (v: unknown): v is ThemeMode => v === 'light' || v === 'dark' || v === 'system';

/** The last theme the main window used, so other windows paint in it before their data arrives. */
export function cachedTheme(): ThemeMode | null {
  const v = storage.get('themeCache');
  return isThemeMode(v) ? v : null;
}

export function cacheTheme(mode: ThemeMode): void {
  storage.set('themeCache', mode);
}

/** The last accent the main window used (see cachedTheme). */
export function cachedAccent(): AccentId {
  const v = storage.get('accentCache');
  return isAccentId(v) ? v : DEFAULT_ACCENT;
}

export function cacheAccent(accent: AccentId): void {
  storage.set('accentCache', accent);
}

/** Accents picked on this device, newest first. */
export function recentAccents(): AccentId[] {
  const v = storage.getJSON<unknown[]>('recentAccents');
  return Array.isArray(v) ? v.filter(isAccentId) : [];
}

/** Remembers a picked accent and returns the updated list. */
export function pushRecentAccent(accent: AccentId): AccentId[] {
  const next = [accent, ...recentAccents().filter(a => a !== accent)].slice(0, RECENT_ACCENTS_MAX);
  storage.setJSON('recentAccents', next);
  return next;
}

/** Reads a design token from the page, e.g. cssVar('--accent'). Tokens live in styles/foundation/tokens.css. */
export function cssVar(name: string, doc: Document = document): string {
  return getComputedStyle(doc.documentElement).getPropertyValue(name).trim();
}

/**
 * A duration token in milliseconds, e.g. cssDurationMs('--dur-2') → 180. JS timers that
 * wait for a CSS animation read the token instead of repeating its value.
 */
export function cssDurationMs(name: string, doc: Document = document): number {
  const raw = cssVar(name, doc);
  const n = parseFloat(raw);
  if (Number.isNaN(n)) return 0;
  return raw.endsWith('ms') ? n : n * 1000;
}
