// SSoT String & UI Dictionary (No hardcoded strings in components)
// Voice guide & full state table: docs/microcopy.md
export const strings = {
  common: {
    cancel: 'Cancel',
    save: 'Save',
    saveChanges: 'Save changes',
    discardChanges: 'Discard changes',
    delete: 'Delete',
    duplicate: 'Duplicate',
    copyOf: '{name} (Copy)',
    edit: 'Edit',
    rename: 'Rename',
    close: 'Close',
    markComplete: 'Mark as complete',
    dragToReorder: 'Drag to reorder'
  },
  app: {
    title: 'Focus Space',
    description: 'A calm, minimal focus timer with sessions, task lists, goals, landmarks, and rewards.'
  },
  // Goal and reward frequencies (types GOAL_FREQUENCIES), plus the "All" filter.
  frequency: {
    all: 'All',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    custom: 'Custom'
  },
  // What each keyboard shortcut does (keys: constants/shortcuts.ts).
  shortcuts: {
    toggleTimer: 'Start or pause the timer',
    skip: 'Skip to the next phase',
    reset: 'Reset the timer',
    newSession: 'New session',
    miniPlayer: 'Open or close the mini player',
    help: 'Open help',
    contextMenu: 'Open the menu for the focused item'
  },
  // Names of keys shown on key caps.
  keys: {
    space: 'Space',
    shift: 'Shift'
  },
  // Compact duration units: formatDuration() in lib/formatUtils.
  units: {
    seconds: '{s}s',
    minutes: '{m}m',
    minutesSeconds: '{m}m {s}s'
  },
  status: {
    ready: 'Ready',
    focusing: 'Focusing…',
    onBreak: 'On a break',
    paused: 'Paused'
  },
  header: {
    notifTooltip: 'Notification settings',
    soundToggleTooltip: 'Toggle sound',
    helpTooltip: 'Help'
  },
  rail: {
    timer: 'Timer',
    tasks: 'Tasks',
    calendar: 'Calendar',
    stats: 'Stats',
    goals: 'Goals',
    rewards: 'Rewards',
    navLabel: 'Main navigation'
  },
  tabs: {
    timer: 'Timer & sessions',
    tasks: 'Tasks',
    calendar: 'Calendar',
    stats: 'Analytics & stats',
    goals: 'Goals & landmarks',
    rewards: 'Rewards'
  },
  timer: {
    focusPhase: 'Focus',
    breakPhase: 'Break',
    noSession: 'Pick a session to start',
    sessionProgress: 'Session progress',
    rewardOnCompletion: 'Reward on completion:',
    sessionsTitle: 'Sessions',
    skipTooltip: 'Skip phase',
    playTooltip: 'Start',
    pauseTooltip: 'Pause',
    nowPlaying: 'Now playing',
    upNext: 'Up next',
    /** Focus sessions finished today (not tasks). */
    completedToday: { one: '{count} focus session done today', other: '{count} focus sessions done today' },
    noOpenTasks: 'No open tasks',
    soundOnTooltip: 'Sound on',
    soundOffTooltip: 'Sound off',
    sessionTasksTitle: 'Session tasks',
    addAnotherList: 'Add another task list',
    pickListPlaceholder: 'Choose a task list…',
    noSessionListsTitle: 'No task list for this session yet',
    noSessionListsHint: 'Pick a list or create a new one. Lists are saved, so any session can reuse them.',
    listInUse: 'In this session',
    collapseList: 'Collapse list',
    expandList: 'Expand list',
    moreListActions: 'List actions',
    remainingAria: '{time} remaining'
  },
  mini: {
    pin: 'Pin position',
    unpin: 'Unpin position',
    alwaysOnTopOn: 'Always on top: on',
    alwaysOnTopOff: 'Always on top: off',
    close: 'Close (timer keeps running)',
    waiting: 'Connecting to Focus Space…',
    windowTitle: 'Focus Space · Mini player',
    progress: 'Progress',
    upNext: 'Up next',
    doneToday: 'Done today',
    noSessionLists: 'This session has no task lists yet. Add one in the app.',
    addToList: 'Add to list'
  },
  tasks: {
    sidebarTitle: 'Lists',
    newListBtn: 'New list',
    selectListPrompt: 'Pick or create a list to get started.',
    addTaskPlaceholder: 'Add a task and press Enter…',
    addTaskBtn: 'Add',
    renameTooltip: 'Rename list',
    duplicateTooltip: 'Duplicate list',
    deleteTooltip: 'Delete list',
    deleteListTitle: 'Delete list?',
    untitledList: 'Task list',
    emptyLists: 'No lists yet. Create one to get started.',
    tasksRemaining: { one: '{count} task remaining', other: '{count} tasks remaining' },
    completedOf: '{done} of {total} completed',
    emptyListPrompt: 'Pick or create a list in the sidebar to start tracking tasks.',
    emptyTasks: 'No tasks yet. Add your first one above.',
    tasksLeft: '{count} left',
    completionTimeTooltip: 'Completion time'
  },
  calendar: {
    prevBtn: 'Previous',
    todayBtn: 'Today',
    nextBtn: 'Next',
    views: {
      week: 'Week',
      day: 'Day',
      month: 'Month'
    },
    quickAddPromptTime: '09:00',
    moreEvents: '+{count} more'
  },
  stats: {
    avgSessionsDay: 'Avg sessions / day',
    avgWorkedDay: 'Avg worked time / day',
    avgTasksCompletedDay: 'Avg tasks completed / day',
    avgTimePerTask: 'Avg time per task',
    productiveDaysTitle: 'Most productive days of the week',
    completionLogsTitle: 'Task completion log',
    emptyLogs: 'No completed tasks yet. Check off tasks during a session and your timing stats will show up here.'
  },
  goals: {
    deleteGoalTitle: 'Delete goal?',
    emptyGoals: 'No goals yet. Set your first one. Small steps count too.',
    landmarksTitle: 'Landmarks',
    untitledGoal: 'Untitled goal',
    untitledLandmark: 'Untitled landmark',
    landmarksCountLabel: '{done} of {total} landmarks',
    dueOn: 'Due {date}',
    startsOn: 'Starts {date}',
    dateRange: '{start} → {end}',
    startsIn: { one: 'starts in {count} day', other: 'starts in {count} days' },
    daysLeft: { one: '{count} day left', other: '{count} days left' },
    dueToday: 'due today',
    overdue: { one: '{count} day past due', other: '{count} days past due' }
  },
  rewards: {
    readyToClaim: 'Ready to claim',
    inProgress: 'In progress',
    claimed: 'Claimed',
    deleteRewardTitle: 'Delete reward?',
    emptyReady: 'Finish a session, landmark or goal to unlock your first reward.',
    linkSessionLabel: 'Link to focus session (optional)',
    noSessionLinked: '— No session linked —',
    linkGoalLabel: 'Link to goal (optional)',
    noGoalLinked: '— No goal linked —',
    noReward: '— No reward —',
    rewardOnCompletion: 'Reward on completion (optional)',
    untitledReward: 'My reward',
    badgeSession: 'Session',
    badgeGoal: 'Goal',
    badgeLandmark: 'Landmark',
    badgeManual: 'Manual'
  },
  sessions: {
    deleteConfirmTitle: 'Delete session?',
    // Shared by sessions, lists, tasks and events — keep it generic.
    deleteConfirmPrompt: 'Delete "{name}"? This can’t be undone.',
    emptySessionsMsg: 'No sessions yet. Create one above to get started.'
  },
  celebration: {
    rewardClaimed: 'Reward claimed',
    desc: 'You earned this one. Enjoy it.',
    awesomeBtn: 'Awesome!'
  },
  notifications: {
    modalTitle: 'Notification settings',
    phaseAlertsLabel: 'Alert me when a phase ends',
    phaseAlertsHint: 'A small popup with a button to start what’s next.',
    enableLabel: 'Remind me before scheduled sessions',
    leadTimeLabel: 'Remind me',
    soundLabel: 'Play a chime',
    autoDismissLabel: 'Hide alerts after',
    autoDismissValue: { one: '{count} second', other: '{count} seconds' },
    browserPermLabel: 'Browser permission',
    requestPermBtn: 'Allow notifications',
    permGrantedMsg: 'Allowed. Alerts reach you even when this tab is in the background.',
    permDefaultMsg: 'Allow notifications so alerts reach you when this tab is in the background.',
    permDeniedMsg: 'Notifications are blocked for this site. Allow them from the icon next to the address, then reload.',
    permUnsupportedMsg: 'This browser can’t show notifications. Alerts still appear inside the app.',
    savedMsg: 'Notification settings saved.',
    options: {
      fiveMin: '5 minutes before',
      tenMin: '10 minutes before',
      fifteenMin: '15 minutes before',
      thirtyMin: '30 minutes before'
    }
  },
  modals: {
    newSession: 'New session',
    editSession: 'Edit session',
    sessionNameLabel: 'Session name',
    sessionNamePlaceholder: 'e.g. Deep work',
    createSessionBtn: 'Create session',
    untitledSession: 'Untitled session',

    newList: 'New task list',
    renameList: 'Rename list',
    listNameLabel: 'List name',
    listNamePlaceholder: 'e.g. Work tasks',
    createListBtn: 'Create list',

    newTask: 'New task',
    renameTask: 'Rename task',
    taskTextLabel: 'Task text',
    taskTextPlaceholder: 'e.g. Design header component',
    addTaskBtn: 'Add task',

    scheduleEvent: 'Schedule session',
    editEvent: 'Edit scheduled session',
    duplicateEvent: 'Duplicate scheduled session',
    titleActivityLabel: 'Title / activity',
    titleActivityPlaceholder: 'e.g. Morning focus session',
    dateLabel: 'Date',
    startTimeLabel: 'Start time',
    durationLabel: 'Duration (minutes)',
    linkedSessionLabel: 'Linked session (optional)',
    standardEventOption: '— Standard event —',
    detailsLabel: 'Details / notes',
    detailsPlaceholder: 'Add specific task notes or goals for this block…',
    defaultEventTitle: 'Scheduled session',

    newGoal: 'New goal',
    editGoal: 'Edit goal',
    goalNameLabel: 'Goal name',
    goalNamePlaceholder: 'e.g. Read 10 books',
    frequencyLabel: 'Frequency',
    createGoalBtn: 'Create goal',

    newLandmark: 'Add landmark',
    editLandmark: 'Edit landmark',
    landmarkNameLabel: 'Landmark name',
    landmarkNamePlaceholder: 'e.g. Finish chapter 3',

    newReward: 'New reward',
    editReward: 'Edit reward',
    rewardNameLabel: 'Reward name',
    rewardNamePlaceholder: 'e.g. Coffee break',
    descriptionLabel: 'Description (optional)',
    descriptionPlaceholder: 'What is this reward?',
    emojiLabel: 'Emoji / icon',
    emojiPick: 'Pick an emoji',
    emojiButtonAria: 'Emoji: {emoji}. Pick another',
    frequencyPeriodLabel: 'Frequency / period',
    createRewardBtn: 'Create reward',

    confirmDeleteTitle: 'Delete item?',
    // ListSidebar replaces the word "item" with the list name — keep exactly one "item".
    confirmDeleteDefaultMsg: 'Delete item? This can’t be undone.',

    focusLabel: 'Focus',
    breakLabel: 'Break',
    minutesSuffix: 'min',
    taskListsLabel: 'Task lists',
    addTaskListPlaceholder: 'Add a task list…',
    newTaskListOption: 'New task list',
    newTaskListPlaceholder: 'List name, then Enter',
    noTaskListsHint: 'No lists yet. Attached lists show under the player on the timer page.',
    removeFromSession: 'Remove from session',
    createRewardOption: 'Create new reward',
    newRewardPlaceholder: 'Reward name, then Enter',
    newRewardTitle: 'New reward',
    pickExistingReward: 'Pick existing instead',
    assignSessionLabel: 'Assign to session (optional)',
    noSessionOption: 'No session',
    createSessionOption: 'Create new session',
    createListAndSessionBtn: 'Create list & set up session',
    newSessionOption: 'New session',
    newSessionPlaceholder: 'Session name, then Enter',
    startDateLabel: 'Start date',
    dueDateLabel: 'Estimated completion',
    optionalHint: 'Optional',
    noDatePlaceholder: 'No date',
    dateOrderError: 'The completion date needs to be on or after the start date.'
  },
  /** Desktop app updates: the launch card (shell/UpdateNotice) and Settings > Updates. */
  updates: {
    sectionTitle: 'Updates',
    notifyLabel: 'Tell me when an update is ready',
    notifyHint: 'Focus Space checks each time it opens.',
    checkBtn: 'Check for updates',
    checking: 'Checking for updates…',
    upToDate: 'You’re up to date. This is version {version}.',
    readyTitle: 'Version {version} is ready',
    readyBody: 'Update now and Focus Space reopens where you left off. Your data stays as it is.',
    installBtn: 'Update and restart',
    laterBtn: 'Maybe later',
    downloading: 'Downloading the update… {percent}%',
    downloadingNoSize: 'Downloading the update…',
    restarting: 'Installing. Focus Space will reopen in a moment.',
    checkFailed: 'We couldn’t check for updates right now. Check your connection and try again.',
    installFailed: 'The update didn’t finish. Your data is safe, so please try again.',
    tryAgainBtn: 'Try again'
  },
  /** The screen shown when a window stops drawing (components/shell/CrashScreen). */
  crash: {
    title: 'Something unexpected happened',
    body: 'Focus Space stopped drawing this screen. Your saved data is safe. Reload to pick up where you left off.',
    reload: 'Reload',
    copyDetails: 'Copy details',
    copied: 'Details copied',
    reportHint: 'If it keeps happening, copy the details and include them when you report it.'
  },
  auth: {
    serverUnreachable:
      'Still connecting to the local app service. We’ll keep trying every few seconds. If it takes a while, start it with npm run dev.',
    signInTitle: 'Welcome back',
    signInSubtitle: 'Sign in to pick up where you left off.',
    setupTitle: 'Let’s set up Focus Space',
    setupSubtitle: 'One quick step, no Next › Next › Finish required. This main account looks after every profile on this device.',
    usernameLabel: 'Username',
    displayNameLabel: 'Display name',
    displayNamePlaceholder: 'e.g. Enzo',
    usernamePlaceholder: 'username',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm password',
    signInBtn: 'Sign in',
    createAccountBtn: 'Create main account',
    fieldRequired: 'A few fields are still empty. Fill them in to continue.',
    passwordsDontMatch: 'Those passwords don’t match yet. Retype them to confirm.',
    weakPassword: 'Passwords need at least {min} characters. Try adding a word or two.',
    switchToLogin: 'Already have an account? Sign in',
    switchToSetup: 'No account? Create the main account',
    signingIn: 'Signing in…',
    creating: 'Setting things up…',
    restoringSession: 'Opening your space…',
    mainAccountTooltip: 'Main account',
    mainBadge: 'Main'
  },
  userMenu: {
    profile: 'Profile',
    appearance: 'Appearance',
    settings: 'Settings',
    exit: 'Sign out'
  },
  profile: {
    title: 'Profile',
    changePhotoBtn: 'Change photo',
    removePhotoBtn: 'Remove photo',
    photoTooLarge: 'That file is over {mb} MB. Try a smaller photo.',
    photoUnreadable: 'We couldn’t read that image. Try a JPG, PNG or WebP photo.',
    nameLabel: 'Name',
    usernameLabel: 'Username',
    savedMsg: 'Profile saved.',
    passwordLabel: 'Password',
    passwordHint: 'Use at least {min} characters.',
    changePasswordBtn: 'Change password',
    keepPasswordBtn: 'Keep current password',
    ruleLength: 'At least {min} characters',
    ruleMatch: 'New passwords match',
    currentPasswordLabel: 'Current password',
    newPasswordLabel: 'New password',
    confirmPasswordLabel: 'Confirm new password',
    passwordChangedMsg: 'Password updated. Other open sessions were signed out to keep things secure.',
    deleteOwnTitle: 'Delete my profile',
    deleteOwnBtn: 'Delete my profile',
    deleteOwnConfirmMsg: 'This removes your profile and everything in it from this device. It can’t be undone.',
    deleteOwnExecMsg: 'Your profile has been deleted.',
    deleteOwnFallback: 'We couldn’t delete your profile. Please try again.'
  },
  appearance: {
    title: 'Appearance',
    themeTitle: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    accentTitle: 'Accent color',
    accentDesc: 'Colors buttons, highlights and the focus timer.',
    recentTitle: 'Recent colors',
    spaceColorsTitle: 'Space colors',
    groups: {
      vibrant: 'Vibrant',
      calm: 'Calm',
      muted: 'Muted'
    },
    colors: {
      'solar-lime': 'Solar lime',
      'starlight-gold': 'Starlight gold',
      sunflare: 'Sunflare',
      'corona-orange': 'Corona orange',
      'red-giant': 'Red giant',
      'pulsar-pink': 'Pulsar pink',
      'nebula-magenta': 'Nebula magenta',
      'nebula-purple': 'Nebula purple',
      'andromeda-violet': 'Andromeda violet',
      'stardust-lavender': 'Stardust lavender',
      'moonlight-blue': 'Moonlight blue',
      'neptune-azure': 'Neptune azure',
      'comet-cyan': 'Comet cyan',
      'aurora-teal': 'Aurora teal',
      'aurora-green': 'Aurora green',
      'supernova-mint': 'Supernova mint',
      sage: 'Sage',
      mint: 'Mint',
      aquamarine: 'Aquamarine',
      sky: 'Sky',
      periwinkle: 'Periwinkle',
      lavender: 'Lavender',
      blush: 'Blush',
      peach: 'Peach',
      concrete: 'Concrete',
      stone: 'Stone',
      taupe: 'Taupe',
      clay: 'Clay',
      'moss-grey': 'Moss grey',
      fog: 'Fog',
      pewter: 'Pewter',
      slate: 'Slate'
    }
  },
  settings: {
    title: 'Settings',
    notificationsTitle: 'Notifications',
    activeBadge: 'Active',
    profilesSectionTitle: 'Profiles',
    profileCounter: '{count} of {max} profiles',
    addProfileBtn: 'Add profile',
    maxProfilesReached: 'You can have up to {max} profiles on this device.',
    addProfileTitle: 'New profile',
    deleteProfileConfirmMsg: 'Delete this profile and everything in it? This can’t be undone.',
    dangerZoneTitle: 'Permanent actions',
    resetProfilesBtn: 'Reset user profiles',
    resetProfilesDesc: 'Removes every user profile and its data. The main account stays.',
    resetConfirmTitle: 'Delete all user profiles?',
    resetConfirmMsg:
      'Every profile except the main account will be removed, along with its goals, rewards and agenda. This can’t be undone.',
    resetPasswordTitle: 'Confirm it’s you',
    resetPasswordMsg: 'Enter your password to confirm.',
    // SettingsView appends " (n)" with the number of profiles removed.
    resetOkMsg: 'User profiles reset'
  },
  help: {
    title: 'Help',
    back: 'Back',
    tourTitle: 'Take the tour',
    tourDesc: 'A one-minute walk through the app.',
    shortcutsTitle: 'Keyboard shortcuts',
    shortcutsDesc: 'Move faster without the mouse.',
    whatsNewTitle: 'What’s new',
    whatsNewDesc: 'Changes in version {version}.',
    aboutTitle: 'About',
    aboutDesc: 'Version, privacy and credits.',
    docsTitle: 'Documentation',
    docsDesc: 'How everything works, on GitHub.',
    reportTitle: 'Report a problem',
    reportDesc: 'Opens GitHub Issues in your browser.',
    starTitle: 'Star on GitHub',
    starDesc: 'If Focus Space helps you, a star helps us.',
    shortcutsNote: 'Shortcuts pause while you’re typing or a dialog is open.',
    whatsNew: [
      'A quick tour for new and returning users. Replay it from Help.',
      'Right-click menus with the actions you need, wherever you click.',
      'Alerts when a phase ends, with a button to start the next one.',
      'A mini player you can resize into a tall or wide layout.',
      'Smoother transitions between pages and timer states.',
      'A tidier profile, with one place to save your changes.',
      'Keyboard shortcuts.',
      'Desktop: a custom window frame, and drag to reorder works again.'
    ],
    versionLabel: 'Version {version}',
    privacyTitle: 'Your data stays here',
    privacyBody: 'Everything is stored on this device and encrypted with your password, and it never leaves it. The desktop app only goes online to see whether an update is out.',
    credits: 'Made by San Milano.',
    licenseNote: 'Free to use and change, including for your work. Selling it, or a version built from it, isn’t allowed.',
    githubLabel: 'GitHub',
    reportBody: 'Version: {version}\nPlatform: {platform}\n\nWhat happened?\n\nWhat did you expect?\n',
    /** The Platform line of bug reports (lib/platform). */
    platformDesktop: 'Desktop ({os})',
    platformWeb: 'Web ({details})',
    platformUnknownOs: 'unknown system'
  },
  onboarding: {
    dialogLabel: 'Tour',
    welcomeTitle: 'Hi {name}, welcome to Focus Space',
    welcomeBody: 'A calm place to focus, one session at a time. Want a quick look around? It takes about a minute.',
    startBtn: 'Show me around',
    laterBtn: 'Maybe later',
    backBtn: 'Back',
    nextBtn: 'Next',
    closeBtn: 'Close tour',
    stepCounter: '{current} of {total}',
    doneTitle: 'You’re all set',
    doneBody: 'Replay this tour anytime from Help, the ? at the top right.',
    doneBtn: 'Start focusing',
    chapters: {
      timer: 'Timer',
      tasks: 'Tasks',
      calendar: 'Calendar',
      stats: 'Stats',
      goals: 'Goals',
      rewards: 'Rewards',
      space: 'Around the app'
    },
    steps: {
      player: { title: 'Your timer', body: 'Sessions play like tracks. Press play to focus, and the break comes right after.' },
      controls: { title: 'Play, reset, skip', body: 'Start or pause, restart the phase, or skip ahead. The space bar works too.' },
      sessions: { title: 'Your sessions', body: 'Each session has its own focus and break length. Drag to reorder, or right-click for more.' },
      sessionTasks: { title: 'Tasks for this session', body: 'Attach task lists to a session to keep them in view while you focus.' },
      lists: { title: 'Task lists', body: 'Group tasks into lists. Any session can reuse them.' },
      listContent: { title: 'Check things off', body: 'Add tasks, drag them into order and tick them off. We time how long each one took.' },
      calendar: { title: 'Plan ahead', body: 'Schedule sessions and drag them to move. We’ll give you a heads-up before each one.' },
      stats: { title: 'See your rhythm', body: 'Daily averages, your most productive days and a log of finished tasks.' },
      goals: { title: 'Goals and landmarks', body: 'Break bigger goals into landmarks and tick them off as you go.' },
      rewards: { title: 'Treat yourself', body: 'Link rewards to sessions or goals. They unlock when you finish, then you claim them here.' },
      nav: { title: 'Get around', body: 'Jump between sections here. Your profile and settings live at the bottom.' },
      status: { title: 'Always in view', body: 'Shows what the timer is doing, even from another page.' },
      mini: { title: 'Mini player', body: 'Keep a small timer on top of other windows while you work.' },
      alerts: { title: 'Alerts', body: 'Choose when we nudge you: when a phase ends and before scheduled sessions.' },
      help: { title: 'Help', body: 'Shortcuts, what’s new and this tour live here.' }
    }
  },
  // Commands, shared by buttons, tooltips, menus and alerts that run the same action.
  actions: {
    newSession: 'New session',
    newList: 'New task list',
    newTask: 'New task',
    scheduleSession: 'Schedule session',
    newGoal: 'New goal',
    newReward: 'New reward',
    startTimer: 'Start timer',
    pauseTimer: 'Pause timer',
    resetTimer: 'Reset timer',
    skipToBreak: 'Skip to break',
    skipToFocus: 'Skip to focus',
    soundOn: 'Turn sound on',
    soundOff: 'Turn sound off',
    openMini: 'Open mini player',
    closeMini: 'Close mini player',
    editSession: 'Edit session',
    startSession: 'Start session',
    help: 'Help and tutorial',
    open: 'Open',
    markNotDone: 'Mark as not done',
    claimReward: 'Claim reward',
    addLandmark: 'Add landmark',
    scheduleHere: 'Schedule session here',
    openDay: 'Open day view',
    openApp: 'Open Focus Space'
  },
  windowControls: {
    minimize: 'Minimize',
    maximize: 'Maximize',
    restore: 'Restore'
  },
  alerts: {
    focusDoneTitle: 'Focus session complete',
    focusDoneBody: 'Nice work. Time for a break.',
    breakDoneTitle: 'Break’s over',
    breakDoneBody: 'Ready when you are.',
    eventSoonTitle: 'Coming up at {time}',
    eventSoonBody: '"{title}" starts in {minutes} min.',
    startBreak: 'Start break',
    startFocus: 'Start focus',
    openApp: 'Open app',
    dismiss: 'Dismiss'
  },
  // Toasts: one short line, past tense for done, present for status. No emoji.
  toasts: {
    setupComplete: 'Setup complete, no restart required. Your space is ready.',
    dataImported: 'Your earlier sessions and tasks came along. Everything’s where you left it.',
    focusComplete: 'Focus session complete. Nice work, time for a break.',
    breakOver: 'Break’s over. Ready when you are.',
    taskDone: 'Task done in {duration}.',
    miniPlayerUnavailable: 'The mini player didn’t open this time. Try again, or keep going here.',
    sessionCreated: 'Session "{name}" is ready.',
    sessionUpdated: 'Session updated.',
    sessionDuplicated: 'Session duplicated.',
    sessionDeleted: 'Session deleted.',
    listCreated: 'List "{name}" is ready.',
    listRenamed: 'List renamed.',
    listDuplicated: 'List duplicated.',
    listDeleted: 'List deleted.',
    taskUpdated: 'Task updated.',
    eventScheduled: '"{title}" is on your calendar.',
    eventMoved: 'Moved to {date} at {time}.',
    eventUpdated: 'Event updated.',
    eventRemoved: 'Event removed.',
    goalCreated: 'Goal "{name}" is set.',
    goalUpdated: 'Goal updated.',
    goalDuplicated: 'Goal duplicated.',
    goalDeleted: 'Goal deleted.',
    rewardCreated: 'Reward "{name}" is ready.',
    rewardUpdated: 'Reward updated.',
    rewardDuplicated: 'Reward duplicated.',
    rewardDeleted: 'Reward deleted.',
    profileRemoved: 'Profile "{name}" removed.'
  },
  // Client-side fallbacks when the server gives no message.
  errors: {
    requestInterrupted: 'Something interrupted that request. Please try again.',
    requestInterruptedCode: 'Something interrupted that request (code {status}). Please try again.',
    // One message per API error code. The web and desktop backends send only
    // { code, params }; params fill the {placeholders}. Keep the codes in sync
    // with server/errors.js and src-tauri/src/backend/errors.rs (npm run audit:errors).
    api: {
      SESSION_EXPIRED: 'Your session has ended. Sign in again to continue.',
      OWNER_ONLY: 'Only the main account can do this.',
      INVALID_USERNAME: 'Usernames use {min}–{max} characters: letters, numbers, dots, dashes or underscores.',
      INVALID_DISPLAY_NAME: 'Display names can be {min}–{max} characters.',
      INVALID_PASSWORD: 'Passwords can be {min}–{max} characters.',
      INVALID_NEW_PASSWORD: 'New passwords can be {min}–{max} characters.',
      USERNAME_TAKEN: 'That username is already in use. Try a different one.',
      ALREADY_SET_UP: 'This device already has a main account. Sign in instead.',
      CREDENTIALS_REQUIRED: 'Enter your username and password to continue.',
      TOO_MANY_ATTEMPTS: 'Too many sign-in attempts in a row. Take a short break and try again in {seconds} seconds.',
      INVALID_CREDENTIALS: 'That username and password don’t match. Check for typos or Caps Lock and try again.',
      CURRENT_PASSWORD_REQUIRED: 'Enter your current password to continue.',
      WRONG_CURRENT_PASSWORD: 'That’s not your current password. Give it another try.',
      PASSWORD_REQUIRED: 'Enter your password to confirm.',
      WRONG_PASSWORD: 'That password doesn’t match. Please try again.',
      OWNER_UNDELETABLE: 'The main account can’t be deleted. It keeps every profile on this device running.',
      PROFILE_LIMIT: 'You’ve reached the limit of {max} profiles. Remove one to add someone new.',
      PROFILE_NOT_FOUND: 'We couldn’t find that profile. It may have been removed already.',
      AVATAR_TOO_LARGE: 'That image is too large. Try a smaller or cropped photo.',
      INVALID_AVATAR: 'That photo couldn’t be saved. Try picking it again.',
      NO_CHANGES: 'No changes to save yet.',
      SAVE_FAILED: 'We couldn’t save that change. Your data is safe, so please try again.',
      PAYLOAD_TOO_LARGE: 'That’s more than we can save at once. Try a smaller image or fewer changes.',
      NOT_FOUND: 'We couldn’t find what you were looking for.',
      INTERNAL: 'Something unexpected happened on our side. Your data is safe, so please try again.'
    },
    createProfile: 'We couldn’t create that profile. Please try again.',
    renameProfile: 'We couldn’t rename that profile. Please try again.',
    deleteProfile: 'We couldn’t delete that profile. Please try again.',
    resetProfiles: 'We couldn’t reset the profiles. Please try again.'
  }
} as const;

export type StringDictionary = typeof strings;
